### ISSUE TITLE
Entity List

### ISSUE THREAD

**Issue by re-learning** [diogoftp/ragnarok-pybot#1]
Hey, very nice repo. I'm also working on learning reverse engineering, doing the same for ragnarok.

I've played around with finding a base address to several things. I'm just hard stuck on the entitylist.
I can find pointers to the CNpc struct (which you called entity) that holds x, y and the id of a mob.

From this point on I tried finding the EntityList, by pointer scanning the CNpc struct of a mob, but there are just too many results.
I have a different client versions, so the offsets are different from yours. 

Would mind elaborating on how you found the entity list?
Thanks!

**Comment by diogoftp** [comment]
Hey !
Thanks for noticing this repo. The entity list was really hard to find, it took me about 1 week. To find it, you can start by finding a monster's address (CNpc instance). I did it by searching for the x or y coordinate of a monster. It will be easier with an immovable monster, because if the monster attacks you back you are going to have 1 more pointer to it, which seems to be a pointer to your current target.
![entity_list_2-2](https://github.com/diogoftp/ragnarok-pybot/assets/31069709/65de3a94-b290-41ee-8f62-5d37e1d1a338)

After you have the address of a coordinate, pointer scan for that address and find look for the pointers that end with the correct coordinate offset. For me, it is 0x16C for the x coordinate and 0x170 for the y coordinate. Start pointer scanning with a max level around 3~6 and increase it if the entity list is not in the results.
![entity_list_2-4](https://github.com/diogoftp/ragnarok-pybot/assets/31069709/77d19991-b2f6-4db8-b497-3873ca256586)

To find the correct entity list offset, copy the address of the first pointer in the chain and use the dissect data structure to analyze it. 
![entity_list_2-5](https://github.com/diogoftp/ragnarok-pybot/assets/31069709/acda261d-8772-4f55-9bc3-8b740abf8b63)
![entity_list_2-6](https://github.com/diogoftp/ragnarok-pybot/assets/31069709/0252c56d-29d6-4522-aadb-fbb224248c07)


Follow the pointer chain, if you are in the correct address, you will go through a pointer of CWorld. Continue following the pointer chain until you find the entity list. It is a double linked list, so it's going to be a pointer to next, pointer to previous, pointer to CNpc.
![entity_list_2-7](https://github.com/diogoftp/ragnarok-pybot/assets/31069709/b0849eee-fe01-4268-965a-f952fe128e8f)
![entity_list_2-8](https://github.com/diogoftp/ragnarok-pybot/assets/31069709/7fa46506-7a32-4488-adfb-f3f9a374e029)
![entity_list_2-9](https://github.com/diogoftp/ragnarok-pybot/assets/31069709/b25a4f3b-75b0-4007-83d7-ddadc3b6a927)


One tip that may help you, is that the base offset of the beginning of the pointer chain is usually 4 bytes before a static address to _current_map.rsw_. So, you can try searching for the string `your_current_map.rsw` and note down the offsets, there were 4 for me. One of them was `ragna4th.exe+B3D1D8`, and the pointer chain for the entity list is `ragna4th.exe+B3D1D4`. I've observed this same behaviour in another servertype.

Please let me know if this helps 😄

**Comment by re-learning** [comment]
Thanks a lot! I actually found it when I reread your readme and saw that it is a doubly linked list. 
Finding CNpc was no problem at all, but I could never find the correct entitylist because it was like 1000+ pointers in the pointer scan.

Since you said that the next and previous nodes are on 0x0 and 0x4 respectively, I just assumed that the CNpc was at 0x8 (lucky yes :D) and I pointer scanned for a pointer with the last three offsets being 0, 8 and 0.

Its only like 3 pointers that way, checked them manually and found it instantly!

I will try the methods you posted as well. Thanks a lot!

**Comment by TaylorAvila** [comment]
Just for your information, if you use ida on the client you can easily find the dwork base and offsets by locating the getactor function. This makes it much easier when debugging new clients. Open it in Lida, locate the getactors string, go to the assembly, decode it and see the offsets there. It's easier than using the cheatengine.

You can see a sub calling dwork right at the beginning. It's this[1], that is, it adds +4 to the dwork address, +204(0xCC), then +16(0x10), then v3 = v1 would be 0x0 and finally this[2](0x8) and +272 = 110. Build this point in the cheatengine and you will locate the structure. I used the translator, so something might have looked strange!

in this case base address 0xccbd14 and {0xCC, 0x10, 0x0, 0x8} then add 0x10C to id


![image2](https://github.com/user-attachments/assets/f5f30f2b-1480-407b-a70a-601b570f4f85)
![image](https://github.com/user-attachments/assets/66b8c2ed-6f83-468e-bff0-2434f7ba5d3f)
